### ISSUE TITLE
Add support for shortcut to home directory when adding rulesets `~/`

### ISSUE THREAD

**Issue by najela** [AtomLinter/linter-phpmd#13]
I use atom on 2 computers so I'll like to add a ruleset just by typing `~/.phpmd/naming.xml` Rather than `Users/najela/.phpmd/naming.xml` since my usernames are different in both computers.

**Comment by steelbrain** [comment]
Well. We just pass the rule sets as-is to the CLI `phpmd`. If you want it to support relative URLs, then I suggest you open up a tracking bug in their repo. :)

**Comment by Arcanemagus** [comment]
@najela I just added an option to automatically search out a `ruleset.xml` file in the current file's directory _or any parent directory_ (which would usually include your home directory). That should probably solve what you are looking for.

Otherwise just put the full path to the `___.xml` file in there, figuring out a solution that expands `~` automatically in a platform agnostic way would require a library and I personally don't really see a point to that...
